# -*- coding: utf-8 -*-
"""
Automatically generated by DeachSword-DearSakura
Author: YinMo (WEDeach)
Version: 1.0.5
"""


class LoginService(object):
    LoginService_REQ_TYPE = 4  # BASE_VAL
    LoginService_RES_TYPE = 4  # BASE_VAL
    LoginService_API_PATH = None  # BASE_VAL

    def __init__(self):
        pass

    def qrCodeLoginForSecure(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 10/31/2022, 08:17:56
        """
        raise Exception("qrCodeLoginForSecure is not implemented")
        METHOD_NAME = "qrCodeLoginForSecure"
        params = []
        sqrd = self.generateDummyProtocol(
            METHOD_NAME, params, self.LoginService_REQ_TYPE
        )
        return self.postPackDataAndGetUnpackRespData(
            self.LoginService_API_PATH, sqrd, self.LoginService_RES_TYPE
        )

    def qrCodeLoginV2ForSecure(
        self, authSessionId: str, modelName: str, systemName: str, secureCode: str
    ):
        """
        qrCode login v2 for secure.

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 10/31/2022, 08:17:56
        """
        METHOD_NAME = "qrCodeLoginV2ForSecure"
        params = [
            [
                12,
                1,
                [
                    [11, 1, authSessionId],
                    [11, 2, systemName],
                    [11, 3, modelName],
                    [11, 5, secureCode],
                ],
            ]
        ]
        sqrd = self.generateDummyProtocol(
            METHOD_NAME, params, self.LoginService_REQ_TYPE
        )
        return self.postPackDataAndGetUnpackRespData(
            "/acct/lgn/sq/v1", sqrd, self.LoginService_RES_TYPE
        )

    def createQrCodeForSecure(self, qrcode):
        """
        create qrCode for secure.

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 10/31/2022, 08:17:56
        """
        METHOD_NAME = "createQrCodeForSecure"
        params = [[12, 1, [[11, 1, qrcode]]]]
        sqrd = self.generateDummyProtocol(
            METHOD_NAME, params, self.LoginService_REQ_TYPE
        )
        return self.postPackDataAndGetUnpackRespData(
            "/acct/lgn/sq/v1", sqrd, self.LoginService_RES_TYPE
        )
