# -*- coding: utf-8 -*-
"""
Automatically generated by DeachSword-DearSakura
Author: YinMo (WEDeach)
Version: 1.0.6
"""

from .BaseService import BaseService, BaseServiceStruct

class RelationService(BaseService):
    RelationService_REQ_TYPE = 4 # BASE_VAL
    RelationService_RES_TYPE = 4 # BASE_VAL
    RelationService_API_PATH = None # BASE_VAL
    
    def __init__(self):
        self.RelationService_API_PATH = "/RE4"


    def getTargetProfiles(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getTargetProfiles is not implemented")
        METHOD_NAME = "getTargetProfiles"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)

    def getUserStatuses(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getUserStatuses is not implemented")
        METHOD_NAME = "getUserStatuses"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)

    def getRecommendationDetails(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getRecommendationDetails is not implemented")
        METHOD_NAME = "getRecommendationDetails"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)

    def getContactCalendarEvents(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getContactCalendarEvents is not implemented")
        METHOD_NAME = "getContactCalendarEvents"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)

    def getBlockDetails(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getBlockDetails is not implemented")
        METHOD_NAME = "getBlockDetails"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)

    def getContactsV3(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getContactsV3 is not implemented")
        METHOD_NAME = "getContactsV3"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)

    def getFriendDetails(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getFriendDetails is not implemented")
        METHOD_NAME = "getFriendDetails"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)

    def addFriendByMid(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!
        
        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("addFriendByMid is not implemented")
        METHOD_NAME = "addFriendByMid"
        params = []
        sqrd = self.generateDummyProtocol(METHOD_NAME, params, self.RelationService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.RelationService_API_PATH, sqrd, self.RelationService_RES_TYPE)